# Generated by Django 4.1.5 on 2023-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=20)),
                ("date_created", models.DateTimeField()),
                ("text_blog", models.TextField(max_length=500)),
            ],
        ),
    ]
