# Generated by Django 4.1.5 on 2023-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="date_created",
            field=models.DateField(),
        ),
    ]
