# Generated by Django 4.1.5 on 2023-01-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogs_date_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blogs",
            new_name="Blog",
        ),
    ]
