# Generated by Django 4.1.5 on 2023-01-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_blogs_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="date_created",
            new_name="date",
        ),
    ]
